### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by DrDub**
This translation is based on the Italian translation. A typo on the
Italian is also fixed.

### CODE REVIEW

**Comment by Peaker** [comment]
Thanks @DrDub (and muchas gracias)! :-)

**Comment by yairchu** [comment]
Thanks!

I have a question that perhaps you can advise,
if I try to use it, with my novice Spanish skills :),
then I feel like abbreviations would be helpful, for example in fibonacci:

Screen Shot 2021-12-16 at 13 40 59

For English for example we have an abbrev. for  "current": "cur"

Screen Shot 2021-12-16 at 13 42 47

I would had added the abbreviations if I had more Spanish knowledge, but I don't know if people even tend to abbreviate, and if they do would "corriente" be abbreviated to "cor"? or "corri"?

**Comment by DrDub** [comment]
Yes, I did feel like abbreviations would be good, but I was basing myself on the Italian that had none. If you want, I can make a pass and provide Spanish abbreviations for entries that have an English abbreviation.

**Comment by yairchu** [comment]
> Yes, I did feel like abbreviations would be good, but I was basing myself on the Italian that had none. If you want, I can make a pass and provide Spanish abbreviations for entries that have an English abbreviation.

That could be great!

**Pull request merged**
