### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kgbvax**
Added missing dependency haskell-stack for mac/homebrew

### CODE REVIEW

**Comment by yairchu** [comment]
So should "requires stack, brew and git" be just "requires brew and git"?

**Comment by kgbvax** [comment]
yes ;-)

**Comment by jedahan** [comment]
like https://github.com/lamdu/lamdu/pull/55 ?

**Comment by yairchu** [comment]
Yeah just like #55 :) Merged that one in. Thanks everyone!

**Pull request closed without merging**
